#!/bin/bash
# CRIU action script for restoring device nodes in a container after restore.
#
# This script is invoked by CRIU during the restore lifecycle via the
# --action-script option. It reads device-mapping.json from the CRIU image
# directory and (re)creates each device node inside the restored container's
# mount namespace so the nodes carry the major:minor numbers of this node.
#
# CRIU environment variables used:
#   CRTOOLS_SCRIPT_ACTION - The current CRIU lifecycle phase (e.g., "post-restore")
#   CRTOOLS_IMAGE_DIR     - Path to the CRIU image directory containing checkpoint files
#   CRTOOLS_INIT_PID      - PID of the restored container's init process
#
# The device-mapping.json file is generated by CRI-O before the restore and
# placed inside $CRTOOLS_IMAGE_DIR. Each entry contains:
#   host_path      - Device path on the host (e.g., /dev/nvidia0)
#   container_path - Expected device path inside the container
#   type           - Device type ("c" for char, "b" for block)
#   major          - Device major number
#   minor          - Device minor number
#
# Installation: /usr/libexec/crio/criu-device-restorer.sh (must be executable)

set -euo pipefail

LOG_TAG="criu-device-restorer"

log_info() {
    logger -t "${LOG_TAG}" "INFO: $*" 2>/dev/null || echo "${LOG_TAG}: INFO: $*" >&2
}

log_warn() {
    logger -t "${LOG_TAG}" "WARN: $*" 2>/dev/null || echo "${LOG_TAG}: WARN: $*" >&2
}

log_error() {
    logger -t "${LOG_TAG}" "ERROR: $*" 2>/dev/null || echo "${LOG_TAG}: ERROR: $*" >&2
}

# Only act on post-restore phase.
if [[ "${CRTOOLS_SCRIPT_ACTION:-}" != "post-restore" ]]; then
    exit 0
fi

MAPPING_FILE="${CRTOOLS_IMAGE_DIR}/device-mapping.json"

# If no device mapping file exists, there is nothing to do.
if [[ ! -f "${MAPPING_FILE}" ]]; then
    log_info "No device-mapping.json found in ${CRTOOLS_IMAGE_DIR}, skipping"
    exit 0
fi

INIT_PID="${CRTOOLS_INIT_PID:-}"
if [[ -z "${INIT_PID}" ]]; then
    log_error "CRTOOLS_INIT_PID is not set, cannot restore device nodes"
    exit 1
fi

# Verify the init process exists.
if ! kill -0 "${INIT_PID}" 2>/dev/null; then
    log_error "Init process ${INIT_PID} does not exist"
    exit 1
fi

log_info "Post-restore device node restore: image_dir=${CRTOOLS_IMAGE_DIR} init_pid=${INIT_PID}"

# Parse the JSON device mapping. We use jq if available, otherwise fall back
# to a simple Python one-liner (python3 is typically available on RHEL/Fedora nodes).
if command -v jq &>/dev/null; then
    ENTRIES=$(jq -r '.[] | "\(.host_path) \(.container_path) \(.type) \(.major) \(.minor)"' "${MAPPING_FILE}")
elif command -v python3 &>/dev/null; then
    ENTRIES=$(python3 -c "
import json, sys
for d in json.load(open(sys.argv[1])):
    print(d['host_path'], d['container_path'], d['type'], d['major'], d['minor'])
" "${MAPPING_FILE}")
else
    log_error "Neither jq nor python3 found, cannot parse device-mapping.json"
    exit 1
fi

FAIL_COUNT=0

while IFS=' ' read -r host_path container_path dev_type major minor; do
    # Skip empty lines
    [[ -z "${host_path}" ]] && continue

    # Verify the host device exists.
    if [[ ! -e "${host_path}" ]]; then
        log_warn "Host device ${host_path} does not exist, skipping"
        continue
    fi

    log_info "Creating device node ${container_path} (type=${dev_type} ${major}:${minor})"

    # Use nsenter to enter the container's mount namespace and recreate the
    # device node there, so it carries the major:minor numbers this node uses.
    #
    # The node must NOT be bind-mounted over afterwards. Everything below runs
    # inside the container's mount namespace, so a "mount --bind host_path
    # container_path" resolves host_path inside the container too: it binds the
    # node onto itself, which changes nothing but leaves one extra mount entry
    # per device in the container's mount table. Those entries are recorded by
    # the next checkpoint and make the restore after it fail inside CRIU with
    # "No mapping for <id>:<path> mountpoint".
    if ! nsenter -t "${INIT_PID}" -m -- /bin/sh -c "
        set -e

        # Ensure the parent directory exists.
        mkdir -p \"\$(dirname '${container_path}')\"

        # Recreate the device node so it points at the current major:minor.
        rm -f '${container_path}' 2>/dev/null || true
        mknod '${container_path}' '${dev_type}' '${major}' '${minor}'
        chmod 0666 '${container_path}'
    "; then
        log_error "Failed to create ${container_path} (${dev_type} ${major}:${minor}) in pid ${INIT_PID}"
        FAIL_COUNT=$((FAIL_COUNT + 1))
    fi
done <<< "${ENTRIES}"

if [[ "${FAIL_COUNT}" -gt 0 ]]; then
    log_error "${FAIL_COUNT} device node(s) failed"
    exit 1
fi

log_info "Device node restore completed successfully"
exit 0
